version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_NETWORK=sepolia
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development environment (optional)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NETWORK=sepolia
    command: npm start
    profiles:
      - dev

  # Smart Contract Development Environment
  hardhat:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8545:8545"
    command: npx hardhat node
    profiles:
      - dev

networks:
  default:
    name: digicats-network
